name: Make JSDocs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDocs
        run: sudo npm install -g jsdoc

      - name: Make Docs
        run: jsdoc -r ./../.. -d ./../../Documentation
