name: Make JSDocs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDocs
        run: sudo npm install -g jsdoc

      - name: Make Docs
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./..
          output_dir: ./../Documentation
          recurse: true

      - name: Save Docs
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: /home/runner/work/CSE-110-Lab-2/Documentation