name: Make JSDocs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Make Docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ../
          recurse: true
          output_dir: ./out