name: Make JSDocs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened]

  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: 'make-docs'
          
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Make Docs
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./src
          output_dir: ./JSDocumentation
          recurse: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./JSDocumentation # The folder the action should deploy.
