name: Make JSDocs
on:
  push:
    branches: [main]
  pull-request:
    branches: [main]

  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    
    uses: andstor/jsdoc-action@v1
    with:
      source_dir: ../
      recurse: true
      output_dir: ./out