name: Make JSDocs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Make Docs
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./src
          output_dir: ./Documentation
          recurse: true

      - name: Push changes to repo
        run: |
          git config --global user.email "bryantshao@gmail.com"
          git config --global user.name "IntelBear"
          git checkout ${{ github.head_ref }}
          git add .
          git status
          git commit -am "Add new comment"
          git push
      - run: |
              cat ./Documentation/hi.js.html
              ls ./Documentation
